server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aldanedev/Proyecto3
          default-label: main
          search-paths: config-data
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
  security:
      user:
        name: root
        password: root
  application:
    name: config-service